github_username: sreerag-kp
snake_dark: "https://raw.githubusercontent.com/sreerag-kp/sreerag-kp/output/github-snake-dark.svg"
snake_light: "https://raw.githubusercontent.com/sreerag-kp/sreerag-kp/output/github-snake.svg"
quote_url: "https://quotes-github-readme.vercel.app/api?type=horizontal&theme=transparent"
streak_url: "https://github-readme-streak-stats-eight.vercel.app/?user=sreerag-kp&theme=transparent&hide_border=true"
stats_url: "http://github-profile-summary-cards.vercel.app/api/cards/stats?username=sreerag-kp&theme=transparent"
most_commit_language_url: "http://github-profile-summary-cards.vercel.app/api/cards/most-commit-language?username=sreerag-kp&theme=transparent"
repos_per_language_url: "http://github-profile-summary-cards.vercel.app/api/cards/repos-per-language?username=sreerag-kp&theme=transparent"
productive_time_url: "http://github-profile-summary-cards.vercel.app/api/cards/productive-time?username=sreerag-kp&theme=transparent&utcOffset=5.30"
profile_details_url: "http://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=sreerag-kp&theme=transparent"
